// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efxehqmwzujsjusxpzte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmeGVocW13enVqc2p1c3hwenRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4Njg4ODYsImV4cCI6MjA2NjQ0NDg4Nn0.2S-dFQoTkuiMvRxpvx7FN2JpJ9g30nyeYvdtN-su6lc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});